### ISSUE TITLE
srcds_linux not executable

### ISSUE THREAD

**Issue by BlackRose01** [Hackebein/docker-srcds#1] opened 2020-04-11 13:40 UTC
Hello,

I would like to run the container with a mounted directory on /opt/steam but the problem is that after the download the file "srcds_linux" is not executable. So could you insert a line in the entrypoint.sh that it would modify the rights of the file so that the program can be execute.

Currently I have to wait until "srcds_linux" is downloaded and between the finish of the download and the start of the server I have to make the file executable with "chmod a+x srcds_linux".

Kind Regards,
BlackRose01

![Unbenannt](https://user-images.githubusercontent.com/7542316/79045365-ff1f9b00-7c0a-11ea-90a8-fc4e5047f61d.PNG)

**Comment by Hackebein** [comment] 2020-04-11 20:19
> I would like to run the container with a mounted directory on /opt/steam but the problem is that after the download the file "srcds_linux" is not executable.

Why should a mounted volume not have the original execution rights? How did you start the container? Can you provide more informations?

I tried it by myself. Basically you start your container with a similar command like ```docker run --rm -it -v "$(pwd):/opt/steam" hackebein/garrysmod```. This is perfectly working for me.

File stat (outside container):
```
# stat srcds_linux
  File: srcds_linux
  Size: 12193           Blocks: 24         IO Block: 4096   regular file
Device: 803h/2051d      Inode: 3325        Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2020-04-11 22:03:47.844175493 +0200
Modify: 2020-04-11 22:03:36.644109193 +0200
Change: 2020-04-11 22:03:37.184112392 +0200
 Birth: -
```

Console output:
```
[...]
Failed to set thread priority: per-thread setup failed
 Update state (0x61) downloading, progress: 53.77 (26437880 / 49164325)
Success! App '4020' fully installed.


************** WARNING ***************
Running the dedicated server as root
is highly discouraged. It is generally
unnecessary to use root privileges to
execute the dedicated server.
**************************************


Auto detecting CPUntinue to launch in 1 secondss
Using default binary: ./srcds_linux
Server will auto-restart if there is a crash.
FIND [/opt/steam/cstrike/*.vpk]
ADDING [/opt/steam/cstrike/cstrike_pak_000.vpk]
Adding Path: [/opt/steam/cstrike]
FIND [/opt/steam/hl2/*.vpk]
ADDING [/opt/steam/hl2/hl2_misc_000.vpk]
Adding Path: [/opt/steam/hl2]
FIND [/opt/steam/hl2mp/*.vpk]
ADDING [/opt/steam/hl2mp/hl2mp_pak_000.vpk]
Adding Path: [/opt/steam/hl2mp]
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Setting breakpad minidump AppID = 4000
Initializing Steam libraries for Workshop..
[S_API] SteamAPI_Init(): Loaded 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
[S_API FAIL] Tried to access Steam interface SteamUser020 before SteamAPI_Init succeeded.
WS: No +host_workshop_collection or it is invalid!
Could not find steamerrorreporter binary. Any minidumps will be uploaded in-processUnknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
Usage: sv_setsteamaccount <login_token>
"host_workshop_collection" = ""
 game
Network: IP 172.17.0.2, mode MP, dedicated Yes, ports 27015 SV / 27005 CL
PREP OK
ConVarRef room_type doesn't point to an existing ConVar
Unknown command "sk_plr_dmg_crowbar"
Unknown command "sk_npc_dmg_crowbar"
Unknown command "sk_plr_dmg_stunstick"
Unknown command "sk_npc_dmg_stunstick"
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Initializing Steam libraries for secure Internet server
[S_API] SteamAPI_Init(): Loaded 'steamclient.so' OK.
CAppInfoCacheReadFromDiskThread took 3 milliseconds to initialize
CApplicationManagerPopulateThread took 0 milliseconds to initialize (will have waited on CAppInfoCacheReadFromDiskThread)
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
Connection to Steam servers successful.
   Public IP is xxx.xxx.xxx.xxx.
Assigned anonymous gameserver Steam ID [A-1:2628716552(14509)].
VAC secure mode is activated.
```

**Comment by BlackRose01** [comment] 2020-04-11 20:38
The container runs on my Synology NAS. So I start it not directly because my NAS offers an app.

These are the file stats:
![List with permissions](https://user-images.githubusercontent.com/7542316/79054408-c4d2ef80-7c44-11ea-82e7-ce3fd8d03a5c.PNG)

![File Stats](https://user-images.githubusercontent.com/7542316/79054420-eaf88f80-7c44-11ea-87eb-730fd112fa0b.PNG)


These are my settings:
```json
[
    {
        "Id": "30cb546290a7cbb10d6dff52cebb36816b21abb4830486a30eca43d6ab16ca79",
        "Created": "2020-04-11T11:31:05.922951792Z",
        "Path": "/entrypoint.sh",
        "Args": [],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 137,
            "Error": "",
            "StartedAt": "2020-04-11T19:09:24.106030481Z",
            "FinishedAt": "2020-04-11T19:58:47.32071336Z",
            "StartedTs": 1586632164,
            "FinishedTs": 1586635127
        },
        "Image": "sha256:099e3f1fed90f12dc9b67bba3b9bfd983d45c4ea9b6523190cca3f68c4d79eb8",
        "ResolvConfPath": "/volume1/@docker/containers/30cb546290a7cbb10d6dff52cebb36816b21abb4830486a30eca43d6ab16ca79/resolv.conf",
        "HostnamePath": "/volume1/@docker/containers/30cb546290a7cbb10d6dff52cebb36816b21abb4830486a30eca43d6ab16ca79/hostname",
        "HostsPath": "/volume1/@docker/containers/30cb546290a7cbb10d6dff52cebb36816b21abb4830486a30eca43d6ab16ca79/hosts",
        "LogPath": "/volume1/@docker/containers/30cb546290a7cbb10d6dff52cebb36816b21abb4830486a30eca43d6ab16ca79/log.db",
        "Name": "/TTT-Server",
        "RestartCount": 0,
        "Driver": "btrfs",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/volume1/Spiele/TTT-Server:/opt/steam:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "db",
                "Config": {}
            },
            "NetworkMode": "bridge",
            "PortBindings": {
                "27015/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "27015"
                    }
                ],
                "27015/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "27015"
                    }
                ],
                "27020/udp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "27020"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "no",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": [],
            "CapDrop": [],
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/steamcmd",
                "DEBIAN_FRONTEND=noninteractive",
                "SIGNALS_ENABLE=false",
                "PORT=27015",
                "TVPORT=27020",
                "CLIENTPORT=27005",
                "SPORT=26900",
                "APPS=4020,232330",
                "AUTHKEY=9342331691B57A6CF8AB5E45C6874AC1",
                "GLSTAPP=4000",
                "GLST=",
                "LOGIN=anonymous",
                "CUSTOMPARAMETERS=",
                "SRCDSPARAMS=\t\t-game garrysmod \t\t-tickrate ${TICKRATE} \t\t-maxplayers ${MAXPLAYERS} \t\t-authkey ${AUTHKEY} \t\t+host_workshop_collection ${WORKSHOPCOLLECTIONID} \t\t+gamemode ${GAMEMODE} \t\t+map ${MAP} \t\t+servercfgfile ${CONFIG} \t\t${CUSTOMPARAMETERS} \t",
                "WORKSHOPCOLLECTIONID=2056647756",
                "TICKRATE=66",
                "MAXPLAYERS=8",
                "GAMEMODE=terrortown",
                "GAMETYPE=0",
                "MAP=gm_flatgrass",
                "MAPGROUP=mg_active",
                "CONFIG=server.cfg"
            ],
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 50,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": null,
            "Name": "btrfs"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/volume1/Spiele/TTT-Server",
                "Destination": "/opt/steam",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "TTT-Server",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "27015/tcp": {},
                "27015/udp": {},
                "27020/udp": {}
            },
            "Tty": true,
            "OpenStdin": true,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/steamcmd",
                "DEBIAN_FRONTEND=noninteractive",
                "SIGNALS_ENABLE=false",
                "PORT=27015",
                "TVPORT=27020",
                "CLIENTPORT=27005",
                "SPORT=26900",
                "APPS=4020,232330",
                "AUTHKEY=9342331691B57A6CF8AB5E45C6874AC1",
                "GLSTAPP=4000",
                "GLST=",
                "LOGIN=anonymous",
                "CUSTOMPARAMETERS=",
                "SRCDSPARAMS=\t\t-game garrysmod \t\t-tickrate ${TICKRATE} \t\t-maxplayers ${MAXPLAYERS} \t\t-authkey ${AUTHKEY} \t\t+host_workshop_collection ${WORKSHOPCOLLECTIONID} \t\t+gamemode ${GAMEMODE} \t\t+map ${MAP} \t\t+servercfgfile ${CONFIG} \t\t${CUSTOMPARAMETERS} \t",
                "WORKSHOPCOLLECTIONID=2056647756",
                "TICKRATE=66",
                "MAXPLAYERS=8",
                "GAMEMODE=terrortown",
                "GAMETYPE=0",
                "MAP=gm_flatgrass",
                "MAPGROUP=mg_active",
                "CONFIG=server.cfg"
            ],
            "Cmd": null,
            "ArgsEscaped": true,
            "Image": "hackebein/garrysmod:latest",
            "Volumes": null,
            "WorkingDir": "/opt/steam",
            "Entrypoint": [
                "/entrypoint.sh"
            ],
            "OnBuild": null,
            "Labels": {},
            "DDSM": false
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "b18080af4dac4536d9584192fbcbdbc1eb8129358c82ac355403e11f47daff1c",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/b18080af4dac",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "fbf6b52b5ccb5a4346d25bc21379c4c21bf70fbde162b745c9c7eaf6d3ee15a1",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

```

**Comment by Hackebein** [comment] 2020-04-11 22:46
It looks like your NAS is typically providing NFS right system. Also it looks like your NAS is reducing the rights of the executable (Maybe for security reasons). I found a lot of people with same or similar problems. The validating and update process of steam is fixing the rights of files like srcds_linux (confirmed by research). An additional chmod doesn't change anything.

I'm sure i can't fix that from the inside of an container, This problem is outside of what a container can do for you.

I see only one way to fix that for you. Mount only the config files as described (https://github.com/Hackebein/docker-garrysmod)

Why are you mounting the whole `/opt/steam` folder?

**Comment by BlackRose01** [comment] 2020-04-14 14:20
Thank you for your answer.

I have to mount the whole folder because I use the pointshop with custom models, custom maps, nextbot and FastDL. This requires the possibility to upload model textures and the shop itself to the addon folder . With nextbot I can create nav files from maps for bots and I don't know where the files will be save.

**Comment by Hackebein** [comment] 2020-04-14 19:13
> pointshop with custom models, custom maps, nextbot and FastDL

I never set that up. Maybe i should look into it to find out what needs to be done for that.

> This requires the possibility to upload model textures and the shop itself to the addon folder

Why aren't you try to mount only `/opt/steam/garrysmod/addons` or `/opt/steam/garrysmod/addons/<addonname>`?

**Comment by Hackebein** [comment] 2020-04-19 15:28
I close this issue because it's an issue with your system.
Anyway i just pushed an other feature, overlay folder. Maybe this helps you to place your files inside the container without mounting `/opt/steam`.

**Closed as completed by Hackebein** 2020-04-19 15:28 UTC
